#!/usr/bin/env python3

import sys
from main import main

def parse_args(args):
    """
    Parse command line arguments in the specified format.

    Args:
        args (list): List of command line arguments.

    Returns:
        dict: Dictionary of parsed arguments.
    """
    parsed_args = {}
    for arg in args:
        if '=' in arg:
            key, value = arg.split('=')
            # Convert boolean values to bool type
            if value.lower() in ['true', 'false']:
                value = value.lower() == 'true'
            parsed_args[key] = value
    return parsed_args

if __name__ == "__main__":
    # Parse command line arguments
    args = parse_args(sys.argv[1:])

    try:
        latitude = float(args.get('latitude'))
        longitude = float(args.get('longitude'))
        radius = float(args.get('radius'))
        use_spark = args.get('use_spark', False)  # Default value: False
        big_data = args.get('big_data', False)  # Default value: False
        verbose = args.get('verbose', False)  # Default value: False

    except (ValueError, TypeError):
        print("Error: Please provide valid values for latitude, longitude, radius, use_spark, big_data, and verbose.")
        sys.exit(1)

    # Call the main function with the new arguments
    main(latitude, longitude, radius, use_spark, big_data, verbose)
